language: ruby
script: rake rspec
sudo: false
rvm:
  - 2.2.2
  - 2.1.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
notifications:
  email:
    - ndushay@stanford.edu
    - laneymcg@stanford.edu
    - cbeer@stanford.edu
