# log_dir:  directory for log file  (default logs, relative to harvestdor gem path)
log_dir: spec/test_logs

# log_name: name of log file  (default: harvestdor.log)

# purl: url for the DOR purl server (used to get ContentMetadata, etc.)
# purl: https://purl-test.stanford.edu
